from typing import Any

class MPV:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def play(self, url: str) -> None: ...
    def stop(self) -> None: ...
    def terminate(self) -> None: ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, value: float) -> None: ...
