from typing import Any, Callable

class pi:
    def __init__(self) -> None: ...
    def set_mode(self, gpio: int, mode: int) -> None: ...
    def set_pull_up_down(self, gpio: int, pud: int) -> None: ...
    def callback(self, gpio: int, edge: int, func: Callable[..., Any]) -> Any: ...
    def stop(self) -> None: ...

INPUT: int
OUTPUT: int
PUD_UP: int
FALLING_EDGE: int
RISING_EDGE: int
EITHER_EDGE: int
