repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-added-large-files
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [--fast]
        files: ^(src|tests)/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args:
          [
            --fix,
            --ignore=E501,
            D100,
            D101,
            D102,
            D103,
            D104,
            D105,
            D106,
            D107,
            D400,
            D415,
            ANN201,
            ANN202,
            ANN001,
            S101,
            SLF001,
            ARG001,
          ]
        files: ^(src|tests)/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args:
          [
            --config-file=mypy.ini,
            --namespace-packages,
            --explicit-package-bases,
          ]
        files: ^src/.*\.py$

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        args:
          [
            "--disable=C0111,C0114,C0115,C0116,E1101,R0801,R0903,W0511,C0103,W1203,W0718,W0621,W0613,W0212,W1514,R0902,R0913,R0914,R0915,R0912,C0301,W0622,W0707,W0603,E0401,C0415,E0611,C2801,W1510,E4703,W0107,R1702,R1705,W0105,R0917,W0719,C0201,C0414,W0602",
          ]
        files: ^(src|tests)/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black]
        files: ^(src|tests)/.*\.py$
