version: '3.8'

services:
  radio:
    build: .
    privileged: true  # Needed for GPIO access
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/snd:/dev/snd"
    ports:
      - "8000:8000"  # API
      - "5173:5173"  # Dev server (if needed)
    volumes:
      - ./src:/home/radio/radio/src  # For development
      - ./config:/home/radio/radio/config
      - ./sounds:/home/radio/radio/sounds
      - ./data:/home/radio/radio/data
      - ./logs:/home/radio/radio/logs
    environment:
      - DEV_MODE=true
      - PYTHONPATH=/home/radio/radio
    restart: unless-stopped 