version: '3.8'

services:
  radio:
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile
    privileged: true # Needed for GPIO access
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/snd:/dev/snd"
    ports:
      - "${API_PORT:-8000}:8000" # API port from settings
      - "${DEV_PORT:-5173}:5173" # Dev server port from settings
    volumes:
      - ./src:/home/radio/radio/src # For development
      - ./config:/home/radio/radio/config
      - ./sounds:/home/radio/radio/sounds
      - ./data:/home/radio/radio/data
      - ./logs:/home/radio/radio/logs
    environment:
      - DEV_MODE=true
      - PYTHONPATH=/home/radio/radio
      - API_PORT=${API_PORT:-8000}
      - DEV_PORT=${DEV_PORT:-5173}
    restart: unless-stopped
