name: radio

services:
  backend:
    container_name: radio-backend
    image: radio-backend
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile.dev
    volumes:
      - ../../src:/home/radio/radio/src
      - ../../config:/home/radio/radio/config
      - ../../tests:/home/radio/radio/tests
      - ../../manage_radio.sh:/home/radio/radio/manage_radio.sh
      - ../../install/requirements.txt:/home/radio/radio/requirements.txt
      - ../../.git:/home/radio/radio/.git
      - ../../sounds:/home/radio/radio/sounds
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - DEV_MODE=true
      - MOCK_SERVICES=${MOCK_SERVICES:-false}
      - API_PORT=8000
      - DEV_PORT=3000
      - CONTAINER_PORT=8000
    command: /home/radio/radio/venv/bin/python -m uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
