name: Nightly Tests

on:
  schedule:
    - cron: "0 0 * * *" # Run daily

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run integration tests
        run: pytest tests/integration/
