name: Radio Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build test image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.test
        load: true
        tags: radio-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Run tests in container
      run: |
        docker run --rm \
          -e MOCK_HARDWARE=true \
          -e TEST_MODE=CI \
          -e DISABLE_HARDWARE=true \
          -e SKIP_NM_CHECK=true \
          -e SKIP_PIGPIO=true \
          -e PIGPIO_MOCK=true \
          -e PYTEST_TIMEOUT=30 \
          -e PYTEST_ASYNCIO_MODE=auto \
          -v ${{ github.workspace }}:/app \
          radio-test:latest \
          pytest -v tests/ \
            --cov=src \
            --capture=no \
            --log-cli-level=DEBUG \
            --asyncio-mode=auto \
            -p no:warnings \
            --ignore=tests/hardware \
            --ignore=tests/integration \
            -k "not test_gpio and not test_hardware"

  check:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Tests passed
        run: echo "All tests passed successfully!"