name: Radio Tests

on:
  push:
    branches: [main, develop]
    paths:
      - "src/**"
      - "tests/**"
      - "config/**"
      - "requirements*.txt"
      - ".github/workflows/**"
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # Set up environment variables
      - name: Set up environment
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "MOCK_HARDWARE=true" >> $GITHUB_ENV
          echo "TEST_MODE=CI" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r install/requirements.txt
          pip install -r install/requirements-dev.txt

      # Debug directory structure
      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "\nDirectory contents:"
          ls -la
          echo "\nTests directory structure:"
          find tests -type d
          echo "\nPython path:"
          echo $PYTHONPATH
          echo "\nTest file contents:"
          find tests -type f -name "test_*.py"

      # Run tests with better error handling
      - name: Run unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          MOCK_HARDWARE: "true"
          TEST_MODE: "CI"
        run: |
          mkdir -p tests/unit tests/api
          python -m pytest \
            --verbose \
            --cov=src \
            --cov-report=xml \
            --junitxml=pytest-results.xml \
            $(find tests -type f -name "test_*.py")

      - name: Run API tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          MOCK_HARDWARE: "true"
          TEST_MODE: "CI"
        run: |
          python -m pytest \
            --verbose \
            --cov=src \
            --cov-append \
            --junitxml=pytest-results.xml \
            $(find tests/api -type f -name "test_*.py")

      # Add test summary
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "pytest-results.xml"
        if: always()
