name: Radio Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        # Install NetworkManager and other dependencies
        sudo apt-get install -y \
          python3-dev python3-setuptools gcc make \
          mpv libmpv-dev \
          python3-pip python3-venv \
          libasound2-dev \
          network-manager  # Add NetworkManager
        
        # Download and build pigpio
        wget https://github.com/joan2937/pigpio/archive/master.zip
        unzip master.zip
        cd pigpio-master
        make
        sudo make install
        
        # Create required directories and set permissions
        sudo mkdir -p /var/run/pigpio
        sudo chmod 777 /var/run/pigpio
        
        # Start services
        sudo systemctl start NetworkManager  # Start NetworkManager
        sudo pigpiod -l -t 0 || true
        
        # Verify NetworkManager is running
        sudo systemctl status NetworkManager
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx pytest pytest-asyncio pytest-cov pytest-mock
        
    - name: Run tests with mocked hardware
      env:
        MOCK_HARDWARE: "true"
        PYTHONPATH: .
        TEST_MODE: "CI"
        DISABLE_HARDWARE: "true"
        # Add environment variable to skip NetworkManager checks in tests
        SKIP_NM_CHECK: "true"
      run: |
        # Run pytest with detailed output
        pytest -v tests/ --cov=src --capture=no --log-cli-level=DEBUG
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  check:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Tests passed
        run: echo "All tests passed successfully!"