name: Radio Tests

on:
  push:
    branches: [main, develop]
    paths:
      - "src/**"
      - "tests/**"
      - "config/**"
      - "requirements*.txt"
      - ".github/workflows/**"
      - "docker/**"
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    # Add fail-fast to stop all jobs if any fail
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Add error handling
        if: success()

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v4
        if: success()
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build with cache
      - name: Build development image
        uses: docker/build-push-action@v5
        if: success()
        with:
          context: .
          file: ./docker/dev/Dockerfile.backend
          load: true
          tags: radio-dev:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Run tests in container with targeted coverage
      - name: Run tests
        if: success()
        run: |
          docker compose -f docker/docker-compose.dev.yml run --rm backend bash -c "
            source /home/radio/radio/venv/bin/activate && \
            mkdir -p tests/unit tests/api tests/integration && \
            python -m pytest \
              --verbose \
              --cov=src/core \
              --cov=src/api \
              --cov=src/hardware \
              --cov-report=xml \
              --cov-report=term-missing \
              --cov-fail-under=80 \
              --junitxml=pytest-results.xml \
              tests/
          "

      # Move cache
      - name: Move cache
        if: success()
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # Add test summary
      - name: Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: "pytest-results.xml"

      # Upload coverage reports
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: success()
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
